const data = `[{"applications":{"path":"/applications","count":345},"things":{"path":"/things","count":226}},{"applications":{"path":"/applications","count":509},"things":{"path":"/things","count":761}},{"applications":{"path":"/applications","count":899},"things":{"path":"/things","count":703}},{"applications":{"path":"/applications","count":789},"things":{"path":"/things","count":395}},{"applications":{"path":"/applications","count":828},"things":{"path":"/things","count":888}},{"applications":{"path":"/applications","count":222},"things":{"path":"/things","count":604}},{"applications":{"path":"/applications","count":646},"things":{"path":"/things","count":18}},{"applications":{"path":"/applications","count":987},"things":{"path":"/things","count":940}},{"applications":{"path":"/applications","count":798},"things":{"path":"/things","count":488}},{"applications":{"path":"/applications","count":626},"things":{"path":"/things","count":938}},{"applications":{"path":"/applications","count":248},"things":{"path":"/things","count":264}},{"applications":{"path":"/applications","count":89},"things":{"path":"/things","count":861}},{"applications":{"path":"/applications","count":8},"things":{"path":"/things","count":54}},{"applications":{"path":"/applications","count":459},"things":{"path":"/things","count":1000}},{"applications":{"path":"/applications","count":123},"things":{"path":"/things","count":943}},{"applications":{"path":"/applications","count":473},"things":{"path":"/things","count":195}},{"applications":{"path":"/applications","count":59},"things":{"path":"/things","count":303}},{"applications":{"path":"/applications","count":131},"things":{"path":"/things","count":49}},{"applications":{"path":"/applications","count":820},"things":{"path":"/things","count":895}},{"applications":{"path":"/applications","count":67},"things":{"path":"/things","count":115}},{"applications":{"path":"/applications","count":53},"things":{"path":"/things","count":384}},{"applications":{"path":"/applications","count":823},"things":{"path":"/things","count":445}},{"applications":{"path":"/applications","count":393},"things":{"path":"/things","count":340}},{"applications":{"path":"/applications","count":199},"things":{"path":"/things","count":421}},{"applications":{"path":"/applications","count":231},"things":{"path":"/things","count":884}},{"applications":{"path":"/applications","count":530},"things":{"path":"/things","count":95}},{"applications":{"path":"/applications","count":824},"things":{"path":"/things","count":656}},{"applications":{"path":"/applications","count":526},"things":{"path":"/things","count":199}},{"applications":{"path":"/applications","count":831},"things":{"path":"/things","count":341}},{"applications":{"path":"/applications","count":892},"things":{"path":"/things","count":634}},{"applications":{"path":"/applications","count":272},"things":{"path":"/things","count":373}}]`;


const getInitialState = () => ({
  detail: JSON.parse(data),
});

export default (state = getInitialState(), action = {}) => {
  return state;
};
